use students
select *from students1
/*1.QUERYING DATA BY USING JOINS AND SUBQUERIES */


SELECT DISTINCT STUDENTS1.ID, STUDENTS1.NAME
FROM STUDENTS1
LEFT JOIN STUDENTS2
ON STUDENTS1.ID = STUDENTS2.ID
ORDER BY STUDENTS1.ID;


SELECT STUDENTS1.ID,STUDENTS1.NAME,STUDENTS1.TOWN,STUDENTS1.PERCENTAGE,STUDENTS1.BRANCH
 FROM STUDENTS1
 JOIN (SELECT MIN(PERCENTAGE) AS PER FROM STUDENTS1)AVG_PER ON STUDENTS1.PERCENTAGE >AVG_PER.PER 
ORDER BY STUDENTS1.ID

select STUDENTS1.ID, STUDENTS1.NAME, STUDENTS1.TOWN, STUDENTS1.PERCENTAGE,STUDENTS1.BRANCH from STUDENTS1 RIGHT join STUDENTS2 on  STUDENTS1.NAME= STUDENTS2.NAME


SELECT *
FROM STUDENTS1
WHERE PERCENTAGE = (
SELECT MAX(PERCENTAGE)
FROM STUDENTS1
);


/*2.MANIPULATE DATA BY USING SQL COMMANDS USING GROUP BY AND HAVING CLAUSE*/
SELECT 
    NAME,
    AVG(PERCENTAGE) AS AVG_PERC
FROM STUDENTS1
GROUP BY NAME
HAVING AVG(PERCENTAGE)> 85
ORDER BY AVG_PERC DESC

SELECT 
    ID,NAME,TOWN ,
    MAX(PERCENTAGE) AS AVG_PERC,BRANCH
FROM STUDENTS1
GROUP BY  ID,NAME,TOWN,BRANCH
HAVING MAX(PERCENTAGE)> 85
ORDER BY AVG_PERC DESC

















