CREATE DATABASE PET_ADOPTIONS

USE PET_ADOPTIONS

CREATE TABLE ANIMALS(
     ID INT,
	 NAME CHAR(225),
	 BREED CHAR(225),
	 COLOR CHAR(225),
	 GENDER CHAR(225),
	 STATUS INT
	 );

	 INSERT INTO DBO.ANIMALS VALUES(1,'BELLYFLOP','BEAGLE','BROWN','M',0),
	                               (2,'SNOWY','HUSKY','WHITE','F',0),
								   (3,'PRINCESS','POMERANIAN','BLACK','F',0),
								   (4,'CRICKET','CHIHUAHUA','BROWN','M',0),
								   (5,'PRINCESS','POODLE','PURPLE','F',0),
								   (6,'SPOT','DALMATION','BLACK&WHITE','M',0);

SELECT *FROM ANIMALS

SELECT BREED FROM ANIMALS

SELECT NAME FROM ANIMALS WHERE GENDER='F'

SELECT ID FROM ANIMALS WHERE STATUS=0


UPDATE ANIMALS SET COLOR='BROWN' WHERE ID=5

UPDATE ANIMALS SET COLOR='BROWN' WHERE NAME='PRINCESS'

SELECT *FROM ANIMALS


DELETE FROM ANIMALS WHERE COLOR='BROWN'

SELECT *FROM ANIMALS


TRUNCATE TABLE ANIMALS

SELECT *FROM ANIMALS


DROP TABLE ANIMALS


USE PET_ADOPTIONS

CREATE TABLE ADOPTIONS(
        ANIMAL_ID INT,
		NAME CHAR(50),
		CONTACT CHAR(50),
		DATES  DATE
		);

INSERT INTO DBO.ADOPTIONS VALUES(1,'PRIYA','PRIYA09@GMAIL.COM',CURRENT_TIMESTAMP),
                                (2,'SAM','SAM22@GMAIL.COM',CURRENT_TIMESTAMP)

ALTER TABLE ADOPTIONS ADD PHONENO INT

SELECT *FROM ADOPTIONS

ALTER TABLE ADOPTIONS DROP  COLUMN PHONENO 

SELECT *FROM ADOPTIONS


