CREATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEE(
        EMPLOYEEID INT,
		NAME VARCHAR(20),
		GENDER VARCHAR(20),
		SALARY INT,
		DEPT VARCHAR(20),
		EXPERIENCE VARCHAR(20)
		);

INSERT INTO DBO.EMPLOYEE VALUES(5,'PRIYA','F',45000,'IT','2YEARS'),
                               (6,'RAHUL','M',65000,'SALES','5YEARS'),
							   (7,'NISHA','F',55000,'MARKETING','4YEARS'),
							   (8,'VIKRAM','M',75000,'FINANCE','7YEARS'),
							   (9,'ARATI','F',50000,'IT','3YEARS');

SELECT *FROM EMPLOYEE;

SELECT DEPT,
SUM(SALARY)AS SALARY
FROM EMPLOYEE
GROUP BY DEPT;


SELECT DEPT,SUM(SALARY)AS SALARY FROM EMPLOYEE GROUP BY DEPT HAVING SUM(SALARY)>=50000;

CREATE TABLE STUDENT(
       NAME VARCHAR(225),
	   MARKS INT
	   );

	   INSERT INTO DBO.STUDENT VALUES('JHON',79),
	                                 ('JOLLY',65),
									 ('SHUZAN',70)


BEGIN TRANSACTION
UPDATE STUDENT SET NAME='SHERLOCK' WHERE NAME='JOLLY';
COMMIT;
ROLLBACK ;

SELECT*FROM STUDENT;

BEGIN TRANSACTION
INSERT INTO STUDENT VALUES('JACK',95);
UPDATE STUDENT SET NAME='ROSSIE' WHERE MARKS=70;
SAVE TRANSACTION A;
INSERT INTO STUDENT VALUES('ZACK',76);
SAVE TRANSACTION B;
INSERT INTO STUDENT VALUES('BRUNO',85);
SAVE TRANSACTION C;

SELECT*FROM STUDENT

ROLLBACK  TRANSACTION A;





